#!/bin/bash

DOTFILES="${HOME}/.dotfiles"
FILES=$GIT/files
LINKS=($(cd $DOTFILES && find . -maxdepth 1 -name '.?*' | cut -c 3-))
GIT_REPO_URL="git@github.com:retraut/dotfiles.git"

function cloneGitRepo() {
    
    mkdir -p $DOTFILES
    git clone $GIT_REPO_URL $DOTFILES
}

function installSymlinks() {

	for i in "${LINKS[@]}"; do
		rm -rf ${HOME}/$i
		if ln -s $FILES/$i ${HOME}/$i; then
			echo Link to ${HOME}/$i created!
		fi
	done
}

function gitsubmoduleUpdate() {

	cd $GIT
	git submodule init
	git submodule update
}

function installVimPackages() {

	vim +PluginInstall +qall
}

function install() {

    cloneGitRepo
	installSymlinks
	installPackages
	gitsubmoduleUpdate
	installVimPackages
}
case "$1" in

install)
	install
	;;
*)
	echo $"Usage: $0 {install|clean|help|status}"
	exit 1

	;;
esac
