#!/bin/bash

GIT="${HOME}/.dotfiles"
DOTFILES=$GIT/files
CONF="${HOME}"
FILES=( $(cd $DOTFILES && find . -maxdepth 1 -name '.?*'| cut -c 3-) )

function install {
for i in "${FILES[@]}"; do
    rm -rf ${HOME}/$i
    if ln -s $DOTFILES/$i ${HOME}/$i ; then
      echo Link to ${HOME}/$i created!
    fi
done
}

function getOS {
   if [ -f /etc/centos-release ]; then 
      ID=centos
	  return
   else
	 source /etc/os-release
   fi
}


function gitsubmodule {
	cd $GIT
	git submodule init
	git submodule update
}

# Need to do in ansible module for centos and ubuntu ( debian ) servers
function needed_package {
	getOS
	if [ $ID == centos ]; then
	    sudo yum install python-pip zsh vim curl wget git -y
    else
		sudo apt-get -y update && sudo apt-get -y upgrade
	    sudo apt-get -y install python-pip zsh vim curl wget git
	fi
}


function update {
	git -C $GIT add .
	git -C $GIT commit
	git -C $GIT push
}

case "$1" in

	install)
		install
		needed_package
		gitsubmodule
	;;

	update)
		update
	;;
	*)
	echo $"Usage: $0 {install|update|clean|help|status}"
	exit 1
      
esac
